#!/bin/bash
# ==============================================================================
# build_combined.sh
#
# Regenerates run_all_combined.js by concatenating the modular scripts in
# dependency order. Run this after editing any of the source files below —
# do not edit run_all_combined.js directly, it will be overwritten.
#
# Usage: bash build_combined.sh   (run from inside gee_scripts/)
# ==============================================================================

set -e

FILES=(
  "region_pipeline.js"
  "regions_config.js"
  "fvc_dynamic_endmember.js"
  "fvc_fixed_endmember.js"
  "wetland_fate_group.js"
  "trend_classification.js"
  "wetland_transition_structure.js"
  "wetland_type_fvc.js"
)

OUT="run_all_combined.js"

cat > "$OUT" << 'HEADER'
/**
 * ==============================================================================
 * run_all_combined.js
 *
 * Single-paste convenience bundle: all 8 modular scripts concatenated in
 * load order, so the entire pipeline can be pasted into one GEE Code
 * Editor script and run in one pass, without switching between files.
 *
 * AUTO-GENERATED by build_combined.sh — do not edit this file directly.
 * Edit the corresponding modular file instead, then re-run:
 *   bash build_combined.sh
 *
 * Order (matches the dependency chain — do not reorder):
 *   1. region_pipeline.js
 *   2. regions_config.js
 *   3. fvc_dynamic_endmember.js
 *   4. fvc_fixed_endmember.js
 *   5. wetland_fate_group.js
 *   6. trend_classification.js
 *   7. wetland_transition_structure.js
 *   8. wetland_type_fvc.js
 *
 * Expect ~42 export tasks to be submitted across all three regions, all
 * saved into a single Drive folder: Wetland_FVC_Exports.
 * ==============================================================================
 */

// Declared once here; the individual module files each redeclare this with
// the same value (harmless under `var`, but de-duplicated in this bundle
// for clarity).
var EXPORT_FOLDER = 'Wetland_FVC_Exports';

HEADER

for f in "${FILES[@]}"; do
  {
    echo ""
    echo "// ══════════════════════════════════════════════════════════════════════════"
    echo "// SECTION: $f"
    echo "// ══════════════════════════════════════════════════════════════════════════"
    echo ""
    # Strip each module's own EXPORT_FOLDER declaration to avoid redeclaring it.
    grep -v "^var EXPORT_FOLDER = 'Wetland_FVC_Exports';$" "$f"
    echo ""
  } >> "$OUT"
done

echo "Wrote $OUT ($(wc -l < "$OUT") lines) from ${#FILES[@]} source files."
