/**
 * ==============================================================================
 * run_all_combined.js
 *
 * Single-paste convenience bundle: all 8 modular scripts concatenated in
 * load order, so the entire pipeline can be pasted into one GEE Code
 * Editor script and run in one pass, without switching between files.
 *
 * AUTO-GENERATED by build_combined.sh — do not edit this file directly.
 * Edit the corresponding modular file instead, then re-run:
 *   bash build_combined.sh
 *
 * Order (matches the dependency chain — do not reorder):
 *   1. region_pipeline.js
 *   2. regions_config.js
 *   3. fvc_dynamic_endmember.js
 *   4. fvc_fixed_endmember.js
 *   5. wetland_fate_group.js
 *   6. trend_classification.js
 *   7. wetland_transition_structure.js
 *   8. wetland_type_fvc.js
 *
 * Expect ~42 export tasks to be submitted across all three regions, all
 * saved into a single Drive folder: Wetland_FVC_Exports.
 * ==============================================================================
 */

// Declared once here; the individual module files each redeclare this with
// the same value (harmless under `var`, but de-duplicated in this bundle
// for clarity).
var EXPORT_FOLDER = 'Wetland_FVC_Exports';


// ══════════════════════════════════════════════════════════════════════════
// SECTION: region_pipeline.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * region_pipeline.js
 *
 * Factory function that builds a fully self-contained processing pipeline for
 * one region (YRD / GBA / BTH). Each call to makeRegionPipeline() creates a
 * new closure — the `roi` and all derived state are locked inside that closure
 * at call time, so pipelines for different regions can never leak into each
 * other, even if a global variable is later reassigned elsewhere in the script.
 *
 * This replaces an earlier architecture where all regions shared the same
 * top-level `roi` variable and a single set of functions. That version caused
 * a real bug: after computing YRD, reassigning `roi` to the GBA boundary and
 * re-running the same functions sometimes still evaluated against YRD's
 * extent, because a function defined earlier had already captured the old
 * `roi` in its closure. The factory pattern makes that class of bug
 * structurally impossible — every function here reads only the `roi`
 * parameter this particular pipeline was built with.
 *
 * Usage:
 *   var pipeYRD = makeRegionPipeline(roi_YRD, 5, 10);
 *   var pipeGBA = makeRegionPipeline(roi_GBA, 4, 11);
 *   var pipeBTH = makeRegionPipeline(roi_BTH, 5, 9);
 *
 * Requires: roi_YRD / roi_GBA / roi_BTH from regions_config.js to already be
 * defined in the same GEE script (GEE has no module import system; scripts
 * in this repo are meant to be read together, not executed as separate
 * files).
 * ==============================================================================
 */

var WETLAND_CODES = [181, 182, 183, 184, 185, 186, 187]; // GLC_FCS30D wetland subtypes

// Single source of truth for wetland-subtype labels. Previously this exact
// 181-187 -> name mapping was independently declared a second time in
// wetland_type_fvc.js and embedded a third time inside the larger land-cover
// dictionary in wetland_transition_structure.js — three copies that could
// silently drift out of sync if one were edited and the others weren't.
// Both of those files now build on this constant instead of restating it.
var WETLAND_TYPE_NAMES = {
  181: 'Swamp', 182: 'Wetland Meadow', 183: 'Floodplain Wetland',
  184: 'Saline Wetland', 185: 'Mangrove', 186: 'Salt Marsh', 187: 'Tidal Flat'
};

// Named scale constants, used across all export scripts instead of bare
// numbers. REGIONAL_SCALE (500m) is used for whole-region mean statistics,
// where the coarser scale is a deliberate speed/cost tradeoff and doesn't
// affect the result at that spatial aggregation. CITY_SCALE (30m) is used
// wherever individual city polygons are the unit of analysis — smaller
// cities were previously found to be silently dropped or biased at 500m —
// and is reused for raster exports (spatial FVC maps, trend classification)
// since 30m also happens to be Landsat's native pixel resolution, which is
// the same "don't lose fine spatial detail" reasoning applied to a
// different kind of output.
var REGIONAL_SCALE = 500;
var CITY_SCALE = 30;

/**
 * @param {ee.Geometry} roi - region boundary, dissolved and simplified upstream
 * @param {number} startMonth - growing-season window start month (region-specific)
 * @param {number} endMonth - growing-season window end month (region-specific)
 * @return {Object} pipeline - see the `return` block at the bottom for the
 *   full list of functions this pipeline exposes.
 */
function makeRegionPipeline(roi, startMonth, endMonth) {

  // ---- GLC_FCS30D land-cover sources, clipped once per region ----
  var imgAnnual = ee.ImageCollection('projects/sat-io/open-datasets/GLC-FCS30D/annual')
    .mosaic().clip(roi);
  var img5Year = ee.ImageCollection('projects/sat-io/open-datasets/GLC-FCS30D/five-years-map')
    .mosaic().clip(roi);

  // Per-year cache for the annual composite. getAnnualCompositeRobust(year)
  // was previously called independently by several export scripts for the
  // same year within a single run (dynamic-endmember export, fixed-endmember
  // export, and the trend-slope computation all need, e.g., year 2020),
  // each time rebuilding the same filter+merge+fallback computation graph
  // from scratch. Caching by year avoids that repeated graph construction
  // within a single pipeline's lifetime.
  var compositeCache = {};

  /**
   * GLC_FCS30D ships two products: a 5-year-interval map for 1985-1995,
   * and an annual map from 2000 onward. This resolves a requested year to
   * the correct source image + band.
   */
  function getBandInfo(year) {
    if (year < 2000) {
      var epochYear = (year < 1988) ? 1985 : (year < 1993) ? 1990 : 1995;
      return { img: img5Year, band: 'b' + ((epochYear - 1985) / 5 + 1) };
    }
    return { img: imgAnnual, band: 'b' + (year - 2000 + 1) };
  }

  /** Binary wetland mask (1 = wetland, 0 = not) for a given year. */
  function getWetlandMask(year) {
    var info = getBandInfo(year);
    return info.img.select(info.band)
      .remap(WETLAND_CODES, ee.List.repeat(1, WETLAND_CODES.length), 0)
      .rename('wetland_mask');
  }

  /** Raw GLC_FCS30D class code (not binarized) — used for transition analysis
   *  and per-wetland-type breakdowns, where the specific subtype matters. */
  function getRawLandCover(year) {
    var info = getBandInfo(year);
    return info.img.select(info.band).rename('landcover_class');
  }

  /**
   * Three-way fate classification between two years:
   *   persistent — wetland at both yA and yB
   *   lost       — wetland at yA, not at yB
   *   gained     — not wetland at yA, wetland at yB
   */
  function getFateMasks(yA, yB) {
    var maskA = getWetlandMask(yA);
    var maskB = getWetlandMask(yB);
    return {
      persistent: maskA.and(maskB).selfMask(),
      lost: maskA.and(maskB.not()).selfMask(),
      gained: maskA.not().and(maskB).selfMask()
    };
  }

  // ---- Landsat surface-reflectance prep (cloud mask + scale to reflectance) ----
  function prepSR_L57(image) {
    var qa = image.select('QA_PIXEL');
    var clear = qa.bitwiseAnd(1 << 4).eq(0).and(qa.bitwiseAnd(1 << 3).eq(0));
    var scaled = image.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B7'])
      .multiply(0.0000275).add(-0.2);
    return scaled.rename(['BLUE', 'GREEN', 'RED', 'NIR', 'SWIR1', 'SWIR2'])
      .updateMask(clear)
      .copyProperties(image, ['system:time_start']);
  }

  function prepSR_L8(image) {
    var qa = image.select('QA_PIXEL');
    var clear = qa.bitwiseAnd(1 << 4).eq(0).and(qa.bitwiseAnd(1 << 3).eq(0));
    var scaled = image.select(['SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7'])
      .multiply(0.0000275).add(-0.2);
    return scaled.rename(['BLUE', 'GREEN', 'RED', 'NIR', 'SWIR1', 'SWIR2'])
      .updateMask(clear)
      .copyProperties(image, ['system:time_start']);
  }

  /** Landsat 5/7 before 2013, Landsat 8 from 2013 onward, filtered to [start, end]. */
  function fetchCollection(year, monthStart, monthEnd) {
    var start = ee.Date.fromYMD(year, monthStart, 1);
    var end = ee.Date.fromYMD(year, monthEnd, 28);
    if (year < 2013) {
      var l5 = ee.ImageCollection('LANDSAT/LT05/C02/T1_L2')
        .filterBounds(roi).filterDate(start, end).map(prepSR_L57);
      var l7 = ee.ImageCollection('LANDSAT/LE07/C02/T1_L2')
        .filterBounds(roi).filterDate(start, end).map(prepSR_L57);
      return l5.merge(l7);
    }
    return ee.ImageCollection('LANDSAT/LC08/C02/T1_L2')
      .filterBounds(roi).filterDate(start, end).map(prepSR_L8);
  }

  /**
   * Annual composite with a 4-level fallback, needed because some
   * region/year combinations (e.g. GBA 1985-1986) have zero usable Landsat
   * scenes within the growing-season window:
   *   1. this year, growing season
   *   2. this year, full year
   *   3. next year, growing season
   *   4. previous year, growing season
   * The image carries an `actual_imagery_year` property recording which
   * level was used, so downstream analysis can flag substituted years
   * rather than silently treating them as the requested year.
   */
  function getAnnualCompositeRobust(year) {
    if (compositeCache[year]) {
      return compositeCache[year];
    }

    var thisYearSeason = fetchCollection(year, startMonth, endMonth);
    var thisYearFull = fetchCollection(year, 1, 12);
    var nextYearSeason = fetchCollection(year + 1, startMonth, endMonth);
    var prevYearSeason = fetchCollection(year - 1, startMonth, endMonth);

    var n0 = thisYearSeason.size();
    var n1 = thisYearFull.size();
    var n2 = nextYearSeason.size();
    var n3 = prevYearSeason.size();

    var chosen = ee.ImageCollection(ee.Algorithms.If(n0.gt(0), thisYearSeason,
      ee.Algorithms.If(n1.gt(0), thisYearFull,
      ee.Algorithms.If(n2.gt(0), nextYearSeason,
      ee.Algorithms.If(n3.gt(0), prevYearSeason, thisYearFull)))));

    var actualYear = ee.Algorithms.If(n0.gt(0), year,
      ee.Algorithms.If(n1.gt(0), year,
      ee.Algorithms.If(n2.gt(0), year + 1,
      ee.Algorithms.If(n3.gt(0), year - 1, year))));

    var composite = ee.Image(chosen.median())
      .clip(roi)
      .set('year', year)
      .set('actual_imagery_year', actualYear);

    compositeCache[year] = composite;
    return composite;
  }

  /**
   * Per-year, per-region dynamic endmembers: the 5th/95th percentile of NDVI
   * across the whole region stand in for "pure soil" and "pure vegetation"
   * for that specific year's imagery. This avoids assuming a single fixed
   * NDVI value holds across 36 years of varying sensors and atmospheric
   * conditions. The tradeoff — endmembers themselves can be noisy in years
   * with few clear pixels — is why a fixed-endmember version exists
   * separately for sensitivity validation (see fvc_fixed_endmember.js).
   */
  function getDynamicEndpoints(ndviImage) {
    var percentiles = ndviImage.reduceRegion({
      reducer: ee.Reducer.percentile([5, 95]),
      geometry: roi, scale: REGIONAL_SCALE, bestEffort: true, tileScale: 8, maxPixels: 1e13
    });
    return {
      soil: ee.Number(percentiles.get('NDVI_p5')),
      veg: ee.Number(percentiles.get('NDVI_p95'))
    };
  }

  // Per-year cache for processIndices — this is the function actually
  // called repeatedly (with overlapping years) across fvc_dynamic_endmember.js,
  // trend_classification.js, wetland_fate_group.js, and wetland_type_fvc.js.
  // Caching the composite alone (above) helps, but the NDVI/EVI/FVC band
  // math and the endmember percentile reduction were still being rebuilt
  // on every call; this cache avoids that too.
  var indicesCache = {};

  /**
   * Computes NDVI / EVI / NDMI / FVC for a given year and returns three
   * masked variants:
   *   all       — no wetland mask (needed for fate-group analysis, where
   *               "lost" pixels are no longer wetland in the mask year)
   *   dynamic   — masked to that year's wetland extent
   *   fixed     — masked to the fixed 1985 wetland baseline
   */
  function processIndices(year) {
    if (indicesCache[year]) {
      return indicesCache[year];
    }

    var rawImg = ee.Image(getAnnualCompositeRobust(year));
    var actualYear = rawImg.get('actual_imagery_year');

    var ndvi = rawImg.normalizedDifference(['NIR', 'RED']).rename('NDVI');
    var evi = rawImg.expression(
      '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))',
      { NIR: rawImg.select('NIR'), RED: rawImg.select('RED'), BLUE: rawImg.select('BLUE') }
    ).clamp(-1, 2).rename('EVI');
    var ndmi = rawImg.normalizedDifference(['NIR', 'SWIR1']).rename('NDMI');

    var endpoints = getDynamicEndpoints(ndvi);
    var fvc = ndvi.subtract(ee.Image.constant(endpoints.soil))
      .divide(ee.Image.constant(endpoints.veg).subtract(ee.Image.constant(endpoints.soil)))
      .clamp(0, 1).rename('FVC');

    var allIndices = ndvi.addBands([evi, ndmi, fvc]);
    var dynamicMask = getWetlandMask(year).selfMask();
    var fixedMask = getWetlandMask(1985).selfMask();

    var result = {
      all: allIndices.set('year', year),
      dynamic: allIndices.updateMask(dynamicMask).set('year', year),
      fixed: allIndices.updateMask(fixedMask).set('year', year),
      endmemberSoil: endpoints.soil,
      endmemberVeg: endpoints.veg,
      actualImageryYear: actualYear
    };

    indicesCache[year] = result;
    return result;
  }

  return {
    roi: roi,
    getWetlandMask: getWetlandMask,
    getRawLandCover: getRawLandCover,
    getFateMasks: getFateMasks,
    getAnnualCompositeRobust: getAnnualCompositeRobust,
    processIndices: processIndices
  };
}


// ══════════════════════════════════════════════════════════════════════════
// SECTION: regions_config.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * regions_config.js
 *
 * Defines the three study-area boundaries and instantiates one independent
 * pipeline per region via makeRegionPipeline() (region_pipeline.js).
 *
 * Load order in the GEE Code Editor: paste region_pipeline.js first, then
 * this file, in the same script.
 *
 * ⚠️ REPRODUCIBILITY WARNING — read before running:
 * `china` below points to a PRIVATE GEE asset under this project's own
 * Google Cloud account. It will NOT be accessible to anyone else who
 * clones this repo — the script will fail on line 1 with a permissions
 * error. This is a known, unresolved gap, not an oversight left
 * undocumented: administrative boundary data with the exact fields this
 * pipeline filters on (`name`, matching Chinese city/district names) was
 * originally sourced this way and has not yet been re-packaged as a
 * public, redistributable dataset.
 *
 * To actually run this pipeline yourself:
 *   1. Obtain a Chinese administrative-boundary dataset with a `name`
 *      field at city/district level (e.g. from GADM, or China's Ministry
 *      of Natural Resources public boundary releases — check each
 *      source's own redistribution terms before use).
 *   2. Upload it as a GEE asset under your own account, or convert it to
 *      a local GeoJSON and load it via `ee.FeatureCollection(ee.Geometry(...))`
 *      instead of the Asset reference below.
 *   3. Replace the `china` variable below with your version. The city
 *      name lists further down (cityFC_YRD / cityFC_GBA / cityFC_BTH)
 *      should not need to change if your dataset's `name` field uses the
 *      same Chinese administrative names.
 * ==============================================================================
 */

var china = ee.FeatureCollection('projects/my-project-11626-475607/assets/China');
var gaul = ee.FeatureCollection('FAO/GAUL_SIMPLIFIED_500m/2015/level2');

// ---------------- Yangtze River Delta (YRD) ----------------
var cityFC_YRD = china.filter(ee.Filter.inList('name', [
  '黄浦区', '徐汇区', '长宁区', '静安区', '普陀区', '虹口区', '杨浦区', '闵行区',
  '宝山区', '嘉定区', '浦东新区', '金山区', '松江区', '青浦区', '奉贤区', '崇明区',
  '南京市', '无锡市', '徐州市', '常州市', '苏州市', '南通市', '连云港市', '淮安市',
  '盐城市', '扬州市', '镇江市', '泰州市', '宿迁市',
  '杭州市', '宁波市', '嘉兴市', '湖州市', '绍兴市', '金华市', '舟山市', '台州市',
  '温州市', '衢州市', '丽水市',
  '合肥市', '芜湖市', '蚌埠市', '淮南市', '马鞍山市', '淮北市', '铜陵市', '安庆市',
  '黄山市', '滁州市', '阜阳市', '宿州市', '六安市', '亳州市', '池州市', '宣城市'
]));
var roi_YRD = cityFC_YRD.geometry().dissolve().simplify(1000);

// ---------------- Greater Bay Area (GBA) — 9 mainland cities + HK + Macao ----------------
var cityFC_GBA = (function () {
  var mainlandNine = china.filter(ee.Filter.or(
    ee.Filter.inList('name', [
      '广州市', '深圳市', '珠海市', '佛山市', '惠州市', '东莞市', '中山市', '江门市', '肇庆市'
    ]),
    ee.Filter.inList('adcode', [440100, 440300, 440400, 440600, 441300, 441900, 442000, 440700, 441200])
  ));
  var hongKong = gaul.filter(ee.Filter.eq('ADM0_NAME', 'Hong Kong')).map(function (f) {
    return f.set('name', '香港');
  });
  var macao = gaul.filter(ee.Filter.eq('ADM0_NAME', 'Macao')).map(function (f) {
    return f.set('name', '澳门');
  });
  return mainlandNine.merge(hongKong).merge(macao);
})();
var roi_GBA = cityFC_GBA.geometry().dissolve().simplify(1000);

// ---------------- Beijing-Tianjin-Hebei (BTH) ----------------
var cityFC_BTH = china.filter(ee.Filter.inList('name', [
  '东城区', '西城区', '朝阳区', '丰台区', '石景山区', '海淀区',
  '门头沟区', '房山区', '通州区', '顺义区', '昌平区', '大兴区',
  '怀柔区', '平谷区', '密云区', '延庆区',
  '和平区', '河东区', '河西区', '南开区', '河北区', '红桥区',
  '东丽区', '西青区', '津南区', '北辰区', '武清区', '宝坻区',
  '滨海新区', '宁河区', '静海区', '蓟州区',
  '石家庄市', '唐山市', '秦皇岛市', '邯郸市', '邢台市',
  '保定市', '张家口市', '承德市', '沧州市', '廊坊市', '衡水市'
]));
var roi_BTH = cityFC_BTH.geometry().dissolve().simplify(1000);

// ---------------- Instantiate one independent pipeline per region ----------------
// Growing-season windows differ by region: YRD/GBA/BTH sit at different
// latitudes and have different vegetation phenology.
var pipeYRD = makeRegionPipeline(roi_YRD, 5, 10);
var pipeGBA = makeRegionPipeline(roi_GBA, 4, 11);
var pipeBTH = makeRegionPipeline(roi_BTH, 5, 9);

var regionPipelines = { YRD: pipeYRD, GBA: pipeGBA, BTH: pipeBTH };
var cityCollections = { YRD: cityFC_YRD, GBA: cityFC_GBA, BTH: cityFC_BTH };

// ---------------- Shared year constants, used across all export scripts ----------------
var nodeYears = [1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020]; // 5-year interval nodes
var years36 = [];
for (var y = 1985; y <= 2020; y++) { years36.push(y); }

// ---------------- Sanity check: areas must be clearly distinct ----------------
// Expected order of magnitude (万 km², i.e. x10^4 km²): YRD ~35, GBA ~5-6, BTH ~21.
// If any two regions print near-identical areas, something upstream leaked
// (e.g. a stale roi reused from a previous pipeline) — stop and check before
// running any exports.
Object.keys(regionPipelines).forEach(function (name) {
  print(name + ' roi area (万 km²):', regionPipelines[name].roi.area().divide(1e10));
});


// ══════════════════════════════════════════════════════════════════════════
// SECTION: fvc_dynamic_endmember.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * fvc_dynamic_endmember.js
 *
 * Core FVC outputs using the dynamic (per-year, per-region) endmember method.
 * Three export products per region:
 *   1. 36-year regional mean time series (dynamic-mask + fixed-1985-mask)
 *   2. City-level FVC at 8 five-year nodes (for the area-vs-quality
 *      four-quadrant analysis)
 *   3. Spatial FVC maps for 1985 and 2020 (30m)
 *
 * Requires: region_pipeline.js and regions_config.js already loaded in the
 * same GEE script (provides regionPipelines, cityCollections, nodeYears,
 * years36).
 * ==============================================================================
 */


/** Product 1: 36-year regional mean FVC/EVI/NDMI, dynamic vs. fixed-1985 mask,
 *  plus the endmember values used each year (kept as columns for auditability —
 *  lets later analysis check whether a given year's endmembers look anomalous). */
function exportYearlyIndices(pipeline, regionName) {
  var yearlyFeatures = years36.map(function (year) {
    var result = pipeline.processIndices(year);
    var dynamicStats = result.dynamic.select(['NDVI', 'EVI', 'NDMI', 'FVC']).reduceRegion({
      reducer: ee.Reducer.mean(), geometry: pipeline.roi, scale: REGIONAL_SCALE, maxPixels: 1e13, tileScale: 8
    });
    var fixedStats = result.fixed.select(['NDVI', 'EVI', 'NDMI', 'FVC']).reduceRegion({
      reducer: ee.Reducer.mean(), geometry: pipeline.roi, scale: REGIONAL_SCALE, maxPixels: 1e13, tileScale: 8
    });
    return ee.Feature(null, {
      region: regionName,
      year: year,
      actual_imagery_year: result.actualImageryYear,
      FVC_Dynamic: dynamicStats.get('FVC'),
      EVI_Dynamic: dynamicStats.get('EVI'),
      NDMI_Dynamic: dynamicStats.get('NDMI'),
      FVC_Fixed1985: fixedStats.get('FVC'),
      EVI_Fixed1985: fixedStats.get('EVI'),
      NDMI_Fixed1985: fixedStats.get('NDMI'),
      NDVI_p5_soil: result.endmemberSoil,
      NDVI_p95_veg: result.endmemberVeg
    });
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(yearlyFeatures),
    description: regionName + '_Indices_36Years',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

/** Product 2: city-level FVC at the 8 five-year nodes — one row per city per
 *  node year, used for the area (wetland extent) vs. quality (FVC) four-
 *  quadrant comparison. Scale is 30m here (finer than the 500m used for
 *  regional means) because city polygons can be small enough that a coarser
 *  scale would miss them entirely. */
function exportCityNodeFVC(pipeline, cityFC, regionName) {
  var cityYearFeatures = nodeYears.map(function (year) {
    var fvcImg = pipeline.processIndices(year).dynamic.select('FVC');
    return fvcImg.reduceRegions({
      collection: cityFC, reducer: ee.Reducer.mean(), scale: CITY_SCALE, tileScale: 8
    }).map(function (f) {
      return f.set('year', year, 'region', regionName);
    });
  }).reduce(function (a, b) {
    return ee.FeatureCollection(a).merge(b);
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(cityYearFeatures),
    description: regionName + '_City_FVC_8Nodes',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

/** Product 3: spatial FVC maps for 1985 and 2020, 30m, dynamic-mask.
 *  These are the source rasters for QGIS visualization and for the trend-
 *  classification script (trend_classification.js), which derives a
 *  per-pixel slope from the full 36-year series rather than these two
 *  endpoint years alone. */
function exportSpatialFVC(pipeline, regionName) {
  var img1985 = pipeline.processIndices(1985).dynamic.select('FVC');
  var img2020 = pipeline.processIndices(2020).dynamic.select('FVC');

  Export.image.toDrive({
    image: img1985.toFloat(),
    description: regionName + '_FVC_1985_30m',
    folder: EXPORT_FOLDER, region: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13
  });
  Export.image.toDrive({
    image: img2020.toFloat(),
    description: regionName + '_FVC_2020_30m',
    folder: EXPORT_FOLDER, region: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  var pipeline = regionPipelines[regionName];
  var cityFC = cityCollections[regionName];

  exportYearlyIndices(pipeline, regionName);
  exportCityNodeFVC(pipeline, cityFC, regionName);
  exportSpatialFVC(pipeline, regionName);

  print('Submitted 4 export tasks for ' + regionName + ' (yearly indices, city nodes, FVC 1985, FVC 2020).');
});

print('All regions submitted. Run the tasks in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');


// ══════════════════════════════════════════════════════════════════════════
// SECTION: fvc_fixed_endmember.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * fvc_fixed_endmember.js
 *
 * Sensitivity check for the dynamic-endmember method used in
 * fvc_dynamic_endmember.js: recomputes FVC using ONE fixed endmember pair
 * per region (that region's 36-year mean of the dynamic endmembers) instead
 * of a fresh endmember every year. If the resulting trend agrees with the
 * dynamic-endmember version, the trend is unlikely to be an artifact of
 * endmember drift. Where they disagree, that disagreement is itself a
 * finding worth reporting (see docs/methodology_notes.md — this is why the
 * full-period 1985-2020 Mann-Kendall test was ultimately abandoned in favor
 * of segmented testing).
 *
 * FIXED_ENDMEMBERS values are each region's 36-year mean of NDVI_p5_soil /
 * NDVI_p95_veg, computed from the CSV output of fvc_dynamic_endmember.js
 * (in Colab: indices_df['NDVI_p5_soil'].mean(), etc.) — not arbitrary
 * constants.
 *
 * Requires: region_pipeline.js and regions_config.js already loaded
 * (provides regionPipelines, cityCollections, nodeYears, years36).
 * ==============================================================================
 */


var FIXED_ENDMEMBERS = {
  YRD: { soil: 0.0905, veg: 0.7897 },
  GBA: { soil: 0.1351, veg: 0.7911 },
  BTH: { soil: 0.2080, veg: 0.7539 }
};

/** Region-level 36-year FVC time series using the fixed endmember pair. */
function exportRegionFixedFVC(pipeline, regionName) {
  var endmember = FIXED_ENDMEMBERS[regionName];

  var rows = years36.map(function (year) {
    var rawImg = pipeline.getAnnualCompositeRobust(year);
    var ndvi = rawImg.normalizedDifference(['NIR', 'RED']).rename('NDVI');
    var fvcFixed = ndvi.subtract(ee.Number(endmember.soil))
      .divide(ee.Number(endmember.veg).subtract(ee.Number(endmember.soil)))
      .clamp(0, 1).rename('FVC_Fixed');

    var dynamicMask = pipeline.getWetlandMask(year).selfMask();
    var stat = fvcFixed.updateMask(dynamicMask).reduceRegion({
      reducer: ee.Reducer.mean(), geometry: pipeline.roi, scale: REGIONAL_SCALE, maxPixels: 1e13, tileScale: 8
    });

    return ee.Feature(null, {
      region: regionName,
      year: year,
      FVC_FixedEndmember_Pixel: stat.get('FVC_Fixed')
    });
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(rows),
    description: regionName + '_FVC_FixedEndmember_PixelLevel',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

/** City-level FVC at the 8 five-year nodes using the fixed endmember pair —
 *  the fixed-endmember counterpart to exportCityNodeFVC() in
 *  fvc_dynamic_endmember.js. Used to re-verify the area-vs-quality
 *  four-quadrant result under a method that cannot be accused of drifting
 *  endmembers between years. */
function exportCityFixedFVC(pipeline, cityFC, regionName) {
  var endmember = FIXED_ENDMEMBERS[regionName];

  var cityYearFeatures = nodeYears.map(function (year) {
    var rawImg = pipeline.getAnnualCompositeRobust(year);
    var ndvi = rawImg.normalizedDifference(['NIR', 'RED']).rename('NDVI');
    var fvcFixed = ndvi.subtract(ee.Number(endmember.soil))
      .divide(ee.Number(endmember.veg).subtract(ee.Number(endmember.soil)))
      .clamp(0, 1).rename('FVC_Fixed');

    var dynamicMask = pipeline.getWetlandMask(year).selfMask();
    var maskedFvc = fvcFixed.updateMask(dynamicMask);

    return maskedFvc.reduceRegions({
      collection: cityFC, reducer: ee.Reducer.mean(), scale: CITY_SCALE, tileScale: 8
    }).map(function (f) {
      return f.set('year', year, 'region', regionName);
    });
  }).reduce(function (a, b) {
    return ee.FeatureCollection(a).merge(b);
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(cityYearFeatures),
    description: regionName + '_City_FixedFVC_8Nodes',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  var pipeline = regionPipelines[regionName];
  var cityFC = cityCollections[regionName];

  exportRegionFixedFVC(pipeline, regionName);
  exportCityFixedFVC(pipeline, cityFC, regionName);

  print('Submitted 2 fixed-endmember export tasks for ' + regionName + '.');
});

print('All regions submitted. Run the tasks in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');


// ══════════════════════════════════════════════════════════════════════════
// SECTION: wetland_fate_group.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * wetland_fate_group.js
 *
 * For each of the 7 adjacent 5-year intervals (1985-1990, ..., 2015-2020),
 * classifies every pixel into persistent / gained / lost wetland (see
 * getFateMasks() in region_pipeline.js) and computes each group's mean FVC.
 *
 * Year convention (the one detail in this script most worth reading
 * carefully):
 *   - persistent, gained -> FVC measured at yB (the interval's end year),
 *     since these pixels ARE wetland at yB.
 *   - lost -> FVC measured at yA (the interval's START year), NOT yB.
 *     A "lost" pixel is by definition no longer wetland at yB, so
 *     measuring it at yB would describe whatever land cover replaced the
 *     wetland (cropland, built-up, etc.), not the wetland itself. The
 *     question this analysis asks is "what did FVC look like on wetlands
 *     right before they were converted?" — which only yA can answer.
 *
 * An earlier version of this script used yB for all three groups. Under
 * yB + the dynamic wetland mask, "lost" pixels are masked out by
 * definition, so the group came back empty. A later fix removed the mask
 * (using the unmasked `.all` index) but still measured at yB — this ran
 * without error, but silently measured the wrong thing: FVC of the new
 * land cover, not of the wetland being lost. Switching lost to yA is the
 * version used here; the underlying finding (lost wetlands generally were
 * not lower-FVC than persistent ones before conversion) held up and, if
 * anything, came out stronger after the fix — this fix did not manufacture
 * the result, so we're not reporting a difference that only exists because
 * of tuning.
 *
 * Requires: region_pipeline.js and regions_config.js already loaded
 * (provides regionPipelines, nodeYears).
 * ==============================================================================
 */


function exportFateGroupFVC(pipeline, regionName) {
  var fateFeatures = [];

  for (var i = 0; i < nodeYears.length - 1; i++) {
    var yA = nodeYears[i];
    var yB = nodeYears[i + 1];
    var fate = pipeline.getFateMasks(yA, yB);

    // persistent/gained: measured at yB (they are wetland at yB)
    var indicesAtB = pipeline.processIndices(yB).all.select('FVC');
    // lost: measured at yA (they were wetland at yA, not at yB)
    var indicesAtA = pipeline.processIndices(yA).all.select('FVC');

    var groups = [
      { type: 'persistent', img: indicesAtB },
      { type: 'gained', img: indicesAtB },
      { type: 'lost', img: indicesAtA }
    ];

    groups.forEach(function (group) {
      var stat = group.img.updateMask(fate[group.type]).reduceRegion({
        reducer: ee.Reducer.mean(), geometry: pipeline.roi, scale: REGIONAL_SCALE, maxPixels: 1e13, tileScale: 8
      });
      fateFeatures.push(ee.Feature(null, {
        region: regionName,
        interval: yA + '-' + yB,
        type: group.type,
        FVC_mean: stat.get('FVC')
      }));
    });
  }

  Export.table.toDrive({
    collection: ee.FeatureCollection(fateFeatures),
    description: regionName + '_FateGroup_FVC',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  exportFateGroupFVC(regionPipelines[regionName], regionName);
  print('Submitted fate-group FVC export for ' + regionName + '.');
});

print('All regions submitted. Run the tasks in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');


// ══════════════════════════════════════════════════════════════════════════
// SECTION: trend_classification.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * trend_classification.js
 *
 * Two related spatial products, both built on a per-pixel linear trend of
 * FVC over the full 1985-2020 series:
 *
 *   1. A 5-level trend classification (severe degradation -> significant
 *      recovery), masked to the region's 2020 wetland extent.
 *   2. A 6-category area-function transition map that layers the trend
 *      classification on top of the wetland fate masks (lost / gained /
 *      persistent), producing categories like "persistent wetland,
 *      degraded" or "newly gained wetland, low cover".
 *
 * Method note: the per-pixel slope here is an ordinary least-squares (OLS)
 * linear fit (ee.Reducer.linearFit()), not Sen's slope. Sen's slope is used
 * for the final reported REGIONAL trend results — a 36-value annual time
 * series of the whole-region mean FVC per region, not a per-pixel
 * computation (see colab_analysis/). GEE's built-in linear-fit reducer used
 * here is OLS, applied per-pixel as a spatial screening tool serving a
 * different, coarser purpose than the regional Sen's-slope result. This
 * raster is therefore not the final trend-significance result — that
 * distinction should stay visible wherever this map is shown.
 *
 * The 5-level class thresholds (±0.001, ±0.005 slope per year) are fixed
 * empirical cut points, not derived from the data distribution. That's a
 * real limitation worth stating plainly rather than implying they were
 * calibrated.
 *
 * Requires: region_pipeline.js and regions_config.js already loaded
 * (provides regionPipelines, years36).
 * ==============================================================================
 */


var TREND_CLASS_LABELS = {
  1: 'Severe Degradation', 2: 'Mild Degradation', 3: 'Stable',
  4: 'Mild Recovery', 5: 'Significant Recovery'
};

var SIX_CATEGORY_LABELS = {
  1: 'Wetland Lost', 2: 'Vegetation Degraded', 3: 'Basically Stable',
  4: 'Vegetation Improved', 5: 'New Low-Cover Wetland (<45%)', 6: 'New High-Cover Wetland (>=45%)'
};

/** Per-pixel OLS slope of FVC over the full 36-year series, computed in
 *  memory each time it's needed (not read from a previously exported
 *  Asset) — an earlier version read a placeholder Asset path that didn't
 *  exist, which is the simpler failure mode to avoid. */
function computeTrendSlope(pipeline) {
  var yearlyFVC = years36.map(function (year) {
    var fvcImg = pipeline.processIndices(year).all.select('FVC');
    return fvcImg.set('year', year).set('system:time_start', ee.Date.fromYMD(year, 6, 1).millis());
  });
  var fvcCollection = ee.ImageCollection(yearlyFVC);

  var fitInput = fvcCollection.map(function (img) {
    var yearBand = ee.Image.constant(img.get('year')).toFloat().rename('year');
    return img.addBands(yearBand);
  });

  return fitInput.select(['year', 'FVC']).reduce(ee.Reducer.linearFit()).select('scale').rename('FVC_slope');
}

/** Maps a continuous slope image to the 5-level class defined above. */
function classifySlope(slope) {
  return slope.expression(
    '(s < -0.005) ? 1 : (s < -0.001) ? 2 : (s <= 0.001) ? 3 : (s <= 0.005) ? 4 : 5',
    { s: slope }
  ).rename('TrendClass').toByte();
}

/** Product 1: 5-level trend classification raster + per-class area (km²).
 *  Takes the already-computed slope and trendClass images rather than
 *  recomputing them — the caller (the per-region loop at the bottom of
 *  this file) computes both once and passes them to both this function
 *  and exportSixCategoryMap(), consistent with the "don't recompute the
 *  expensive 36-year linear fit" principle stated above. classifySlope()
 *  itself is cheap (a pixel-wise expression, not a reduction), so calling
 *  it twice wouldn't have been a real performance problem — but doing so
 *  would have been inconsistent with that stated principle, and easy for
 *  a reviewer to notice and question. */
function exportTrendClassification(pipeline, regionName, slope, trendClass) {
  var mask2020 = pipeline.getWetlandMask(2020).selfMask();
  var trendClassMasked = trendClass.updateMask(mask2020);
  var slopeMasked = slope.updateMask(mask2020);

  Export.image.toDrive({
    image: trendClassMasked,
    description: regionName + '_FVC_TrendClass_5Level',
    folder: EXPORT_FOLDER, region: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13
  });
  Export.image.toDrive({
    image: slopeMasked.toFloat(),
    description: regionName + '_FVC_Slope_Raw',
    folder: EXPORT_FOLDER, region: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13
  });

  var pixelAreaKm2 = ee.Image.pixelArea().divide(1e6);
  var areaStats = pixelAreaKm2.addBands(trendClassMasked).reduceRegion({
    reducer: ee.Reducer.sum().group({ groupField: 1, groupName: 'class_id' }),
    geometry: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13, tileScale: 8
  });

  var labels = ee.Dictionary(TREND_CLASS_LABELS);
  var areaFeatures = ee.List(areaStats.get('groups')).map(function (d) {
    d = ee.Dictionary(d);
    var classId = ee.Number(d.get('class_id'));
    return ee.Feature(null, {
      region: regionName,
      class_id: classId,
      class_label: labels.get(classId.format()),
      area_km2: d.get('sum')
    });
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(areaFeatures),
    description: regionName + '_FVC_TrendClass_AreaStats',
    folder: EXPORT_FOLDER, fileFormat: 'CSV'
  });
}

/**
 * Product 2: 6-category area-function transition map, combining fate
 * (lost/gained/persistent between 1985 and 2020) with the trend class for
 * persistent wetland, and a 45% FVC threshold for newly gained wetland to
 * split "low-cover" from "high-cover":
 *   1 Wetland Lost              — wetland in 1985, not in 2020
 *   2 Vegetation Degraded       — persistent, trend class 1-2
 *   3 Basically Stable          — persistent, trend class 3
 *   4 Vegetation Improved       — persistent, trend class 4-5
 *   5 New Low-Cover Wetland     — gained, 2020 FVC < 45%
 *   6 New High-Cover Wetland    — gained, 2020 FVC >= 45%
 *
 * 45% threshold: corresponds to the boundary between "moderate-low" and
 * "moderate" vegetation cover in the 5-level classification of SL 190-2007
 * (中华人民共和国水利部, 《土壤侵蚀分类分级标准》 — a water-resources industry
 * standard, not a national GB/T standard): 0-30% / 30-45% / 45-60% / 60-75% /
 * 75-100%. This classification table is confirmed via a secondary academic
 * citation of the standard, not a direct reading of the primary standard
 * text — treat it as well-supported but not independently verified against
 * the original document.
 *
 * Cross-validated against wetland_transition_structure.js's transition
 * matrix — see docs/methodology_notes.md for the full three-round
 * diagnosis of an earlier ~1.7-2.2x discrepancy between the two, which
 * turned out to be a scope mismatch (this map counts ALL wetland change;
 * the transition matrix's core analysis counts only cropland + built-up
 * conversions) rather than a computation error in either script.
 */
function exportSixCategoryMap(pipeline, regionName, trendClass) {
  var mask1985 = pipeline.getWetlandMask(1985);
  var mask2020 = pipeline.getWetlandMask(2020);
  var fvc2020 = pipeline.processIndices(2020).all.select('FVC');

  var lost = mask1985.and(mask2020.not());
  var gained = mask1985.not().and(mask2020);
  var persistent = mask1985.and(mask2020);

  var persistentDegraded = persistent.and(trendClass.lte(2));
  var persistentStable = persistent.and(trendClass.eq(3));
  var persistentImproved = persistent.and(trendClass.gte(4));

  var gainedLowCover = gained.and(fvc2020.lt(0.45));
  var gainedHighCover = gained.and(fvc2020.gte(0.45));

  var sixClass = ee.Image(0)
    .where(lost, 1)
    .where(persistentDegraded, 2)
    .where(persistentStable, 3)
    .where(persistentImproved, 4)
    .where(gainedLowCover, 5)
    .where(gainedHighCover, 6)
    .rename('SixClass')
    .selfMask();

  var pixelAreaKm2 = ee.Image.pixelArea().divide(1e6);
  var areaStats = pixelAreaKm2.addBands(sixClass).reduceRegion({
    reducer: ee.Reducer.sum().group({ groupField: 1, groupName: 'class_id' }),
    geometry: pipeline.roi, scale: CITY_SCALE, maxPixels: 1e13, tileScale: 8
  });

  var labels = ee.Dictionary(SIX_CATEGORY_LABELS);
  var areaFeatures = ee.List(areaStats.get('groups')).map(function (d) {
    d = ee.Dictionary(d);
    var classId = ee.Number(d.get('class_id'));
    return ee.Feature(null, {
      region: regionName,
      class_id: classId,
      class_label: labels.get(classId.format()),
      area_km2: d.get('sum')
    });
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(areaFeatures),
    description: regionName + '_SixCategory_AreaStats',
    folder: EXPORT_FOLDER, fileFormat: 'CSV'
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  var pipeline = regionPipelines[regionName];
  // Computed once, shared by both exports below — this is the expensive
  // step (36-year per-pixel linear fit), so it must not be recomputed.
  var slope = computeTrendSlope(pipeline);
  var trendClass = classifySlope(slope);

  exportTrendClassification(pipeline, regionName, slope, trendClass);
  exportSixCategoryMap(pipeline, regionName, trendClass);
  print('Submitted trend-classification + six-category exports for ' + regionName + '.');
});

print('All regions submitted. Run the tasks in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');


// ══════════════════════════════════════════════════════════════════════════
// SECTION: wetland_transition_structure.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * wetland_transition_structure.js
 *
 * Independent of the FVC analysis line (fvc_*.js, wetland_fate_group.js,
 * trend_classification.js) — this script only needs wetland masks and raw
 * land-cover codes, not vegetation indices, so it runs as its own export
 * batch even though it shares the same pipelines.
 *
 * Two products per region:
 *   1. Transition structure: for each of the 7 adjacent 5-year intervals,
 *      what specific land-cover class did lost wetland convert INTO, and
 *      what specific land-cover class did gained wetland convert FROM.
 *      This is the finer-grained counterpart to the binary wetland mask —
 *      it answers "lost to what" rather than just "lost or not".
 *   2. City-level wetland area at the 8 five-year nodes, used alongside
 *      the FVC line's city-level FVC (fvc_dynamic_endmember.js) for the
 *      area-vs-quality four-quadrant analysis.
 *
 * Cross-check note: water body (class 210) typically accounts for the
 * large majority of raw transition-matrix totals (a known artifact —
 * suspected classification drift at wetland/water boundaries in
 * GLC_FCS30D, not real large-scale wetland-to-water conversion). Any
 * downstream analysis of this CSV should filter out class 210 before
 * interpreting "what wetland converted to", and the core cropland +
 * built-up conversion figures should be read as the higher-confidence
 * subset — not the full unfiltered total. See docs/methodology_notes.md
 * for the reasoning behind this filter and how it was cross-validated
 * against the six-category map in trend_classification.js.
 *
 * Requires: region_pipeline.js and regions_config.js already loaded
 * (provides regionPipelines, cityCollections, nodeYears, WETLAND_CODES,
 * and WETLAND_TYPE_NAMES — this script builds its class dictionary from
 * those rather than restating the 181-187 mapping a third time; see
 * region_pipeline.js for why that consolidation matters).
 * ==============================================================================
 */

var WETLAND_CODES_LIST = ee.List(WETLAND_CODES);

// Full GLC_FCS30D class dictionary, used to label whatever class wetland
// pixels converted to/from — not just "wetland vs. not". Non-wetland
// classes are specific to this script (transition analysis is the only
// place they're needed); the wetland subtype names are pulled from
// WETLAND_TYPE_NAMES so there is exactly one place that mapping lives.
var NON_WETLAND_CLASS_NAMES = {
  10: 'Rainfed Cropland', 11: 'Herbaceous Cover Cropland', 12: 'Tree/Shrub Cover Cropland', 20: 'Irrigated Cropland',
  51: 'Open Evergreen Broadleaved Forest', 52: 'Closed Evergreen Broadleaved Forest',
  61: 'Open Deciduous Broadleaved Forest', 62: 'Closed Deciduous Broadleaved Forest',
  71: 'Open Evergreen Needle-Leaved Forest', 72: 'Closed Evergreen Needle-Leaved Forest',
  81: 'Open Deciduous Needle-Leaved Forest', 82: 'Closed Deciduous Needle-Leaved Forest',
  91: 'Open Mixed Leaf Forest', 92: 'Closed Mixed Leaf Forest',
  120: 'Shrubland', 121: 'Evergreen Shrubland', 122: 'Deciduous Shrubland',
  130: 'Grassland', 140: 'Lichens and Mosses', 150: 'Sparse Vegetation',
  152: 'Sparse Shrubland', 153: 'Sparse Herbaceous',
  190: 'Impervious Surface', 200: 'Bare Land', 201: 'Consolidated Bare Land', 202: 'Unconsolidated Bare Land',
  210: 'Water Body', 220: 'Permanent Snow/Ice'
};

function mergeDictionaries(a, b) {
  var merged = {};
  Object.keys(a).forEach(function (k) { merged[k] = a[k]; });
  Object.keys(b).forEach(function (k) { merged[k] = b[k]; });
  return merged;
}

var LANDCOVER_CLASS_NAMES = ee.Dictionary(mergeDictionaries(WETLAND_TYPE_NAMES, NON_WETLAND_CLASS_NAMES));

/** Product 1: for each interval, what wetland transitioned into (direction
 *  'out') and what became wetland from (direction 'in'), broken down by
 *  the specific land-cover class involved. */
function exportTransitionStructure(pipeline, regionName) {
  var rows = [];

  for (var i = 0; i < nodeYears.length - 1; i++) {
    var yA = nodeYears[i];
    var yB = nodeYears[i + 1];

    var lcA = pipeline.getRawLandCover(yA);
    var lcB = pipeline.getRawLandCover(yB);
    var wetA = lcA.remap(WETLAND_CODES_LIST, ee.List.repeat(1, WETLAND_CODES.length), 0);
    var wetB = lcB.remap(WETLAND_CODES_LIST, ee.List.repeat(1, WETLAND_CODES.length), 0);

    // out: wetland at yA, not wetland at yB -> record what it became (lcB)
    var outMask = wetA.eq(1).and(wetB.eq(0));
    var outStats = summarizeByClass(lcB.updateMask(outMask), pipeline.roi);
    rows.push(labelDirection(outStats, regionName, yA, yB, 'out'));

    // in: not wetland at yA, wetland at yB -> record what it came from (lcA)
    var inMask = wetA.eq(0).and(wetB.eq(1));
    var inStats = summarizeByClass(lcA.updateMask(inMask), pipeline.roi);
    rows.push(labelDirection(inStats, regionName, yA, yB, 'in'));
  }

  Export.table.toDrive({
    collection: ee.FeatureCollection(rows).flatten(),
    description: regionName + '_WetlandTransitionStructure',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

/** Groups a class-code image by pixel area (km²) within roi. */
function summarizeByClass(classImage, roi) {
  return ee.Image.pixelArea().divide(1e6).addBands(classImage).reduceRegion({
    reducer: ee.Reducer.sum().group({ groupField: 1, groupName: 'class' }),
    geometry: roi, scale: CITY_SCALE, maxPixels: 1e13, tileScale: 8
  });
}

/** Converts the grouped reduceRegion output into labeled Features. */
function labelDirection(stats, regionName, yA, yB, direction) {
  return ee.FeatureCollection(ee.List(stats.get('groups')).map(function (d) {
    d = ee.Dictionary(d);
    var code = ee.Number(d.get('class'));
    return ee.Feature(null, {
      region: regionName,
      interval: yA + '-' + yB,
      direction: direction,
      converted_class_code: code,
      converted_class_name: LANDCOVER_CLASS_NAMES.get(code, 'Unknown'),
      area_km2: d.get('sum')
    });
  }));
}

/** Product 2: city-level wetland area (km²) at the 8 five-year nodes —
 *  pairs with exportCityNodeFVC() in fvc_dynamic_endmember.js for the
 *  area-vs-quality four-quadrant analysis. */
function exportCityWetlandArea(pipeline, cityFC, regionName) {
  var rows = nodeYears.map(function (year) {
    var wetlandMask = pipeline.getWetlandMask(year);
    var areaImg = ee.Image.pixelArea().divide(1e6).updateMask(wetlandMask).rename('wetland_area_km2');
    return areaImg.reduceRegions({
      collection: cityFC, reducer: ee.Reducer.sum(), scale: CITY_SCALE, tileScale: 8
    }).map(function (f) {
      return f.set('year', year, 'region', regionName);
    });
  }).reduce(function (a, b) {
    return ee.FeatureCollection(a).merge(b);
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(rows),
    description: regionName + '_City_WetlandArea_8Nodes',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  var pipeline = regionPipelines[regionName];
  var cityFC = cityCollections[regionName];

  exportTransitionStructure(pipeline, regionName);
  exportCityWetlandArea(pipeline, cityFC, regionName);

  print('Submitted transition-structure + city-wetland-area exports for ' + regionName + '.');
});

print('All regions submitted (' + Object.keys(regionPipelines).length * 2 + ' tasks). ' +
  'Run them in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');


// ══════════════════════════════════════════════════════════════════════════
// SECTION: wetland_type_fvc.js
// ══════════════════════════════════════════════════════════════════════════

/**
 * ==============================================================================
 * wetland_type_fvc.js
 *
 * Breaks FVC down by the 7 specific GLC_FCS30D wetland subtypes (report
 * section 3.11), rather than treating "wetland" as one undifferentiated
 * mask as the other scripts do. Three snapshot years (1985 / 2000 / 2020)
 * rather than the full 36-year series — this is a lighter, lower-risk
 * addition run late in the project, not part of the core trend analysis.
 *
 * Uses getRawLandCover() (specific class codes) rather than
 * getWetlandMask() (binary wetland/not) — the binary mask can't
 * distinguish Mangrove from Swamp, which is the whole point here.
 *
 * Requires: region_pipeline.js and regions_config.js already loaded
 * (provides regionPipelines, and WETLAND_TYPE_NAMES which this script
 * reuses rather than redeclaring — see region_pipeline.js for why that
 * consolidation matters).
 * ==============================================================================
 */

var SNAPSHOT_YEARS = [1985, 2000, 2020];

function exportByWetlandType(pipeline, regionName) {
  var rows = [];

  SNAPSHOT_YEARS.forEach(function (year) {
    var fvcImg = pipeline.processIndices(year).all.select('FVC');
    var rawLandCover = pipeline.getRawLandCover(year);

    Object.keys(WETLAND_TYPE_NAMES).forEach(function (codeStr) {
      var code = parseInt(codeStr, 10);
      var typeMask = rawLandCover.eq(code);
      var stat = fvcImg.updateMask(typeMask).reduceRegion({
        reducer: ee.Reducer.mean(), geometry: pipeline.roi, scale: REGIONAL_SCALE, maxPixels: 1e13, tileScale: 8
      });
      rows.push(ee.Feature(null, {
        region: regionName,
        year: year,
        wetland_code: code,
        wetland_type: WETLAND_TYPE_NAMES[code],
        FVC_mean: stat.get('FVC')
      }));
    });
  });

  Export.table.toDrive({
    collection: ee.FeatureCollection(rows),
    description: regionName + '_FVC_ByWetlandType',
    folder: EXPORT_FOLDER,
    fileFormat: 'CSV'
  });
}

// ---------------- Run for all three regions ----------------
Object.keys(regionPipelines).forEach(function (regionName) {
  exportByWetlandType(regionPipelines[regionName], regionName);
  print('Submitted by-wetland-type FVC export for ' + regionName + '.');
});

print('All regions submitted. Run the tasks in the Tasks tab under the ' + EXPORT_FOLDER + ' folder.');

